package comprehensive;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Random;
import java.util.Scanner;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Represents a grammar used to generate random phrases.
 * 
 * A grammar contains non-terminals mapped to lists of possible productions.
 * The grammar is read from a properly formatted input file. Phrases are
 * generated by beginning with the {@code <start>} non-terminal and recursively
 * expanding all non-terminals until only terminal characters remain.
 * 
 * @author Sophia Schluth and Tanishka Bista
 * @version 7.28.2026
 */
public class Grammar {
	
	private HashMap<String, ArrayList<String>> grammar;
	private Random random;
	
	/**
	 * Constructs a grammar by reading its non-terminal definitions and
	 * productions from the given file.
	 *
	 * @param file the grammar file to parse
	 */
	public Grammar(File file) {
		grammar = new HashMap<>();
		random = new Random();
		
		parseFile(file);
	}
	
	/**
	 * Generates and returns one random phrase from this grammar.
	 *
	 * Phrase generation begins with the {@code <start>} non-terminal. Each
	 * non-terminal is randomly replaced by one of its possible productions.
	 *
	 * @return a randomly generated phrase
	 */
	public String generatePhrase() {
		StringBuilder phrase = new StringBuilder();
		expand(getRandomWord("<start>"), phrase);
		return phrase.toString();
	}
	
	/**
	 * Recursively expands all non-terminals in the given production and appends
	 * the resulting terminal characters to the provided string builder.
	 *
	 * Characters outside angle brackets are appended directly to the result.
	 * When a non-terminal is found, one of its productions is selected randomly
	 * and recursively expanded.
	 *
	 * @param production the production to expand
	 * @param result the string builder to which the expanded phrase is appended
	 */
	private void expand(String production, StringBuilder result) {
		for (int i = 0; i < production.length(); i++) {
			if (production.charAt(i) == '<') {
				int end = production.indexOf('>', i);
				String key = production.substring(i, end + 1);

				expand(getRandomWord(key), result);
				i = end;
			}
			else {
				result.append(production.charAt(i));
			}
		}
	}
	
	/**
	 * Randomly selects one production belonging to the specified non-terminal.
	 *
	 * @param key the non-terminal whose productions are being selected from
	 * @return one randomly selected production
	 */
	private String getRandomWord(String key) { 
		ArrayList<String> values = grammar.get(key);
		int randInt = random.nextInt(values.size());
		
		return values.get(randInt);
	}
	
	/**
	 * Reads the grammar file and stores each non-terminal and its productions.
	 *
	 * Lines outside curly braces are ignored. Within each definition, the first
	 * line is the non-terminal and each following line until the closing curly
	 * brace is one possible production.
	 *
	 * @param file the grammar file to parse
	 */
	private void parseFile (File file) {
		try (Scanner scanner = new Scanner(file)) {
			while (scanner.hasNextLine()) {
				String line = scanner.nextLine();
				
				if (line.equals("{")) {
					String key = scanner.nextLine();
					ArrayList<String> values = new ArrayList<>();
					
					line = scanner.nextLine();
					
					while (!line.equals("}")) {
						values.add(line);
						line = scanner.nextLine();
					}
					
					grammar.put(key, values);
				}
				
			}
		}
		catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * Creates a grammar for timing experiments.
	 *
	 * The grammar contains the requested number of non-terminals. Each
	 * non-terminal has two productions. The first production expands to the next
	 * non-terminal, and the second expands to a terminal word. The final
	 * non-terminal expands only to terminal words.
	 *
	 * @param nonTerminalCount the number of non-terminals to include
	 * @return a Grammar containing the generated rules
	 */
	/**
	 * Creates a grammar for timing how the number of non-terminals affects phrase
	 * generation.
	 *
	 * The grammar contains the requested total number of non-terminals, including
	 * {@code <start>}. Phrase generation always expands the same number of
	 * non-terminals, while the remaining definitions are unused.
	 *
	 * @param nonTerminalCount the total number of non-terminals in the grammar
	 * @return a Grammar containing the generated rules
	 */
	public static Grammar createTimingGrammar(int nonTerminalCount) {
		if (nonTerminalCount < 2) {
			throw new IllegalArgumentException(
					"The grammar must contain at least two non-terminals.");
		}

		try {
			File temp = File.createTempFile("timingGrammar", ".g");
			temp.deleteOnExit();

			try (PrintWriter out = new PrintWriter(new FileWriter(temp))) {
				// Starting non-terminal
				out.println("{");
				out.println("<start>");
				out.println("<N1>");
				out.println("}");

				// The only non-terminal used when generating a phrase
				out.println("{");
				out.println("<N1>");
				out.println("word");
				out.println("phrase");
				out.println("}");

				// Additional unused non-terminals
				for (int i = 2; i < nonTerminalCount; i++) {
					out.println("{");
					out.println("<N" + i + ">");
					out.println("word");
					out.println("phrase");
					out.println("}");
				}
			}

			return new Grammar(temp);
		}
		catch (IOException e) {
			throw new RuntimeException("Unable to create timing grammar.", e);
		}
	}
}
